### PR TITLE
Implemented handling of EXT-X-ENDLIST in the parser

### PR DESCRIPTION
**Pull request by Wopple**
The parsing API has been updated.

### CODE REVIEW

**Comment by Wopple** [comment]
I'm thinking of not including the README changes until the latest release includes the updated API.

**Comment by derjust** [comment]
Leaving the README behind might be a good idea to ensure that the documentation on the github page matches the currently available/most recent artifacts in Maven.

And https://pages.github.com/ sounds a little bit too complicated for the given API complexity

**Comment by derjust** [comment]
:+1 
Maybe replacing `IOException` with `EOFException` in d39f54f but the rest looks nice

**Comment by Wopple** [comment]
I didn't know about `EOFException`. +1

**Pull request closed without merging**
