### PR TITLE
hashCode() and equals() method for all data containers as per #11

### PR DESCRIPTION
**Pull request by derjust**
hashCode() and equals() method for all data containers as per #11

### CODE REVIEW

**Comment by Wopple** [comment]
The `equals` implementations can definitely be cleaned up with `ObjectUtil.equals`. See `MediaData.equals` for reference.

**Comment by Wopple** [comment]
Oh, it looks like you removed ObjectUtil. Why was that?

**Comment by derjust** [comment]
I think those `equals` methods are easier to debug and have those quick-checks at the beginning (different class or same object) which make them "better".
But that is for sure a very subjective opinion. Happy to use your ObjectUtils approach (any reason to use that as it looks like it is also part of Dravik: https://developer.android.com/reference/java/util/Objects.html ?)

**Comment by Wopple** [comment]
I was unaware of the `Objects` class. Yes, please make use of it! +1

We will optimize when performance becomes an issue in practice. For now, let's keep the code clean.

**Comment by derjust** [comment]
Please review whenever it fits. 
Followed old concept of `ObjectUtil` but replaced it with its counterpart from JDK1.7 / Dravik doing the exact same code.

**Pull request closed without merging**
